name: workshop
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - jupyterlab>=2.0.0
  - numpy
  - pip
  - plotly
  - typing_extensions
  - pip:
      - nbzip
      - nbgitpuller
      - pymatgen
      - atomate>=0.9.5
      - matminer>=0.6.3
      - pymongo==3.10.1
      - robocrys>=0.2.4
      - crystal-toolkit>=2020.6.4
      - mpcontribs-client>=3.2.0
      - automatminer
      - yapf
